[package]
name = "aquiline-rblx/aqua"
description = "Aqua is a collection of useful libraries for Luau development"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"