name: Publish

on: push

jobs: 

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Setup aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install aftman Toolchains
        run: aftman install

      - name: Install Dependencies
        run: wally install --project-path src/

      - name: Create Packages Directory
        run: mkdir -p Packages

      - name: Get Release from wally.toml
        uses: SebRollen/toml-action@v1.0.0
        id: read_toml
        with: 
          file: 'src/wally.toml'
          field: 'package.version'


      - name: Publish to Wally
        env: 
          WALLY_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
        run: |
          mkdir =p ~/.wally
          printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_TOKEN" >> ~/.wally/auth.toml
          wally publish